### ISSUE TITLE
Improve translation import/export functionality

### ISSUE THREAD

**Issue by Tatuk** [dialob/dialob-parent#104]
The current translation export generates a CSV file where the order of rows don't follow the order of defined dialog items which makes it quite difficult to follow. BTW do we have issue with custom type dialog items?? 

Also we should have better instruction how to use translations as translations can only happen for LATEST (which is correct) version. But as the LATEST is dynamic then there is (fairly big) chance  that exported translation file and LATEST at time the translation is done have miss match....Okay functionality 2 will partly resolve this but this needs to be clearly define

1. We should improve this by forcing the export structure follow **same structure** as given dialog has and by adding additional following columns to export file. NOTE this additional columns are only used for sorting purposes thus Item ID only primary key

ItemID, **PageID**, **ParentID **ItemType**, Description, fi, sv, ......

Where:
PageID to indicates where this translation item is used. For global list PageID is Root
ParentID that indicates to what it the parent of this item belongs. (this a bit 
ItemType == Label, Validation, List (choice or multi choice)...

2. Do pre check of TO BE imported translation file against the dialog that ALL the ItemID are matched. If it don't matched it should report which are not found and then given user option to accept or decline the import process. 

At the moment translation import works for both scenarios translation as more Item ID's than LATEST or translations has less Item ID's that the LATEST. This okay behaviour atm

**Comment by admirkrilasevic** [comment]
Done as part of https://github.com/dialob/dialob-parent/issues/114
