### ISSUE TITLE
Context/express variable editor improvements

### ISSUE THREAD

**Issue by Tatuk** [dialob/dialob-parent#109]
The current context variable editor, Variables menu item, needs some small improvements to improve its usability

1. It should indicate those context variables that are used in dialog as dialog can also have context variables that ARE not used in given dialog. An indicator that show this to user.
2. User should be able to write a short description of this context variable. Like "This variable is used for ......". Lets limit the max length for these info txt only
3. Make possible to move rows
4. Remove Published selection? This needs to be checked @villuv ?

**Comment by admirkrilasevic** [comment]
Resolved via https://github.com/dialob/dialob-parent/pull/126
