### ISSUE TITLE
New Composer: Translation CSV upload / download

### ISSUE THREAD

**Issue by villuv** [dialob/dialob-parent#114]
- Functionality for improved translation CSV upload / download should be ported to new composer and should remain compatible with the file format
- the old translation management UI ("understood") is not required, only the way to add/remove languages + CSV upload/download is needed
- CSV generation and parsing logic should be in separate files / functions, not built directly into UI components

**Comment by admirkrilasevic** [comment]
Design available here, on the "Translations dialog" page: https://www.figma.com/file/yLaToUvAVnB2BRlabjIXlO/Dialob-Composer?type=design&node-id=61%3A2&mode=design&t=3EmcgjPekfWoLdzT-1
