### ISSUE TITLE
New Dialob composer does not open new forms

### ISSUE THREAD

**Issue by jocelynmutso** [dialob/dialob-parent#143]
**Expected behaviour:** Upon creating a new form in the Admin view, the Composer should open an enable the user to start editing it. 

**Problem description:** I created a **new** form this morning on 1 June, and the Composer can't seem to open it. The Composer is stuck in Loading.

Previously-existing forms open fine with no problems.

The form in question is here: https://demo.dialob.io/composer/jarvenpaa-feedback-form-jocelyn?tenantId=7c0161b5-2956-48c0-8aad-36b5763d560e

<img width="1728" alt="Screenshot 2024-06-01 at 09 42 42" src="https://github.com/dialob/dialob-parent/assets/47987958/4a64dc98-3efd-420c-9629-73c50f7b02fd">

**Comment by admirkrilasevic** [comment]
Resolved via #142
