### ISSUE TITLE
Unable to delete visibility/requirement rules + unexpected UI crashes when attempting to do so

### ISSUE THREAD

**Issue by jocelynmutso** [dialob/dialob-parent#144]
1. Any value entered in a validation/requirement rule field cannot be deleted and persists when you close the editing dialog and open it again.

2. Editing these fields can sometimes cause the UI to crash unexpectedly.

https://github.com/dialob/dialob-parent/assets/47987958/3539343b-641b-4c06-8d94-f2a769394046

**Comment by admirkrilasevic** [comment]
Resolved via #142
