### ISSUE TITLE
Editing and saving behaviour for the key in Choice item is different from editing the value 

### ISSUE THREAD

**Issue by jocelynmutso** [dialob/dialob-parent#145]
When creating a list, there seems to be an issue with editing the key: 

As soon as you stop typing in the "key" field, the value is auto-saved and the editor collapses unexpectedly.

When you are editing the actual value via "Add choice translation", things work as expected.

I'm not sure if this is the intended behaviour or not.

https://github.com/dialob/dialob-parent/assets/47987958/b818e682-3c26-4355-82a3-b32a6cad2864

**Comment by admirkrilasevic** [comment]
Resolved via #142
