### ISSUE TITLE
Choice item editing dialog should scroll up to new item fields in the case of long lists

### ISSUE THREAD

**Issue by jocelynmutso** [dialob/dialob-parent#146]
Sometimes, a Choice list can be quite long. In this case, when adding a new list item/item translation at the end of an already long list, the new item's fields should be scrolled into view instead of having to scroll down to them manually.

https://github.com/dialob/dialob-parent/assets/47987958/bed22aec-9f8b-4b1d-a1ee-fc8a0c3ac42a

**Comment by admirkrilasevic** [comment]
Resolved via #142
