### ISSUE TITLE
State problem when changing itemId 

### ISSUE THREAD

**Issue by jocelynmutso** [dialob/dialob-parent#147]
When editing an itemId, it is possible to correctly save the new value. 

However, there seems to be some sort of state error when trying to change the value back to the original.  Saving the change back to the original value requires closing the dialog and opening it again.  

https://github.com/dialob/dialob-parent/assets/47987958/4f9cd978-5806-403e-b133-102565029e58

**Comment by admirkrilasevic** [comment]
Resolved via #142
