### ISSUE TITLE
Problems when editing both itemId and translation in new item

### ISSUE THREAD

**Issue by jocelynmutso** [dialob/dialob-parent#148]
When creating a new item, there is an issue with saving the label value if you have edited the itemId.

Unpredictably, this label-saving problem also happens occasionally when editing a previously-created item. I am not able to reliably produce this error, but it does happen from time to time.

https://github.com/dialob/dialob-parent/assets/47987958/3160f8c9-5d0a-4fe3-8481-9dc03e5de6e7

**Comment by admirkrilasevic** [comment]
Resolved via #142
