### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by jocelynmutso** [dialob/dialob-parent#149]
After using the new Composer for a couple hours to create a test form, I have some initial "quality of life" suggestions based on my experiences as an actual user.  This is just my opinion, of course, but perhaps it is useful nonetheless.

# Suggestions

## “Add translation” field should appear by default in the currently active Form locale

If I am working with a form whose active locale is English, naturally I will be adding label translations in English by default.  It makes sense that this label translation field would appear  by default without having to manually click the “add translation” button to add it, while additional locales are added by clicking the button.

## It should be possible to delete label translations

I'm not sure if this is expected behaviour, but once I add a label translation, there is no obvious way to delete it.  The only possible action is to clear the text value, but what I truly want is to remove the field altogether.

## Consider changing the ordering of the fields in the Choice editing tab

The order of fields in the Choice editing tab feels a bit awkward.  First you have key, and then a rule editor, and the label value is hidden by default until you click the button to add a translation.  When I make lists, I like to add the key and value at the same time, and the rule comes last.  It might feel more natural if key and value were physically closer to each other, both visible by default at the same time, and not separated by a rule editor line.   

Perhaps it would make sense to put the key/value on the same line.  I am not sure that a key (or even a value, for that matter) requires an entire line for the value, but that's just my opinion.

<img width="1543" alt="Screenshot 2024-06-01 at 12 12 57" src="https://github.com/dialob/dialob-parent/assets/47987958/2637f254-a985-4bf3-b775-4e36e0bccfc2">

## Expand all / Collapse all buttons in Explorer should be combined into one toggle button

I think the natural tendency of expand/collapse buttons is that they toggle.  But here, we have two separate buttons.  It feels a bit unnatural to have to click on a separate button when I want to expand and then collapse this menu tree.

## New fields added to the bottom of the Page should be scrolled into view

When I add new items from the “Add item” button within a group, the view correctly scrolls up to show these new fields. However, if I click the “Add item” on the Page level at the bottom, new items are added “under” the current view and it doesn’t scroll up to show them.

## Consider adding a list of available properties and their descriptions to the "Properties" tab.

We all know that, unless you **know** what they are, there is no obvious way to enter properties.  I am sure this has been discussed for years, but maybe now would be a good time to figure out a good way how to display the available options to the user and give some explanation of what they do.

**Comment by admirkrilasevic** [comment]
Suggestions implemented in #142
