### ISSUE TITLE
Closing the item edit dialog too quickly loses changes

### ISSUE THREAD

**Issue by jocelynmutso** [dialob/dialob-parent#150]
When editing item label translations, I discovered that, if you add a new translation and then "too quickly" click the "Close" button on the item edit dialog, the changes are not saved to the backend.  

https://github.com/dialob/dialob-parent/assets/47987958/ba178a01-7f36-468c-bc8b-8663686b09e2

**Comment by admirkrilasevic** [comment]
Resolved via #142
