### ISSUE TITLE
Note rendering issue with large integers

### ISSUE THREAD

**Issue by villuv** [dialob/dialob-parent#169]
When entering a large number (more than 12 digits) into a "number" input, note referring to that value disappears from the filling items.

No visible errors in logs.

**Reproduction**
Example form: https://demo.dialob.io/composer/vvBigNumber?tenantId=7c0161b5-2956-48c0-8aad-36b5763d560e
Start typing digits into the field and watch the note disappear after certain number of digits has been entered.

**Comment by patope** [comment]
Fixed in #183
