### ISSUE TITLE
Change of ID name used in multirow group visibility/required rules create an error

### ISSUE THREAD

**Issue by Tatuk** [dialob/dialob-parent#212]
To replicate
1) Create a multirow group + add couple elements there
2) Create a visibility rule to created group
3) Change the ID name used to control visibility of created multirow group

and you get following error

<img width="284" alt="Screenshot 2024-10-08 at 7 27 35" src="https://github.com/user-attachments/assets/3c5c6059-2573-4c3e-bc1d-b1fb6033c7d7">

to make the dialog work again you need to delete all the elements in the multirow group first and then the group it self

**Comment by villuv** [comment]
I think the (backend side) variable ID renamer is not rewriting the addrow rules. Other "new" rules should be checked also.

**Comment by Tatuk** [comment]
so i guess the this falls to @patope

**Comment by villuv** [comment]
Doesn't matter, I can do it too
