### ISSUE TITLE
dialob backend and composer version number should be visible in composer

### ISSUE THREAD

**Issue by villuv** [dialob/dialob-parent#53]
**Backend**
Check if backend version number is exposed, if not make it exposed (actuator endpoint)

**Composer**
Include package version and package name in built package, expose backend and composer versions in UI (Options -> Information page)

**Comment by villuv** [comment]
Backend version information is exposed by actuator on `/manage/info`

**Comment by Tatuk** [comment]
@admirkrilasevic this definitely should be available new composer

**Comment by admirkrilasevic** [comment]
Implemented in https://github.com/dialob/dialob-parent/pull/135

Version info is located inside of options dialog
