### ISSUE TITLE
Material Composer: Group display improvement / suggestion

### ISSUE THREAD

**Issue by jocelynmutso** [dialob/dialob-parent#97]
These suggestions are to improve the way that Groups and nested Groups are displayed.

1. Groups are **NOT** visually nested.
2. Groups **are** indicated with **Tabs** containing the **groupId**. 
3. The **nesting path** of a child is indicated with a **helper** text/breadcrumb.
4. All items have two modes: **Edit** mode and **View** mode.
5. **Groups** are distinguished by a **coloured Tab** at the top left corner.
6. In Edit mode, everything besides groups has a vertical coloured indicator on the left side.

**Top level group**

![groups1 drawio](https://github.com/dialob/dialob-parent/assets/47987958/fe1c4626-08c5-4dc9-aed6-d9f2832bc6a0)

---

**Nested group**

![groups2 drawio](https://github.com/dialob/dialob-parent/assets/47987958/689eff83-ca3c-4859-8774-1e8529aaf270)

**Comment by villuv** [comment]
In new composer, item attributes are not "inline" editable any more, so the edit mode described here is not needed.

"Active item" concept exists also in the old implementation. I would add here keyboard navigation with up/down arrow keys moving the active selection up/down, possibly having also other hotkey shortcuts for other functions applied to the active item.

**Comment by villuv** [comment]
About group nesting, how would following structure look like using your concept:

![image](https://github.com/dialob/dialob-parent/assets/497068/432ab722-ae80-4666-8d13-e10bef3d058a)

Showing first page, there may be others, the page item tree is:
- group1
  - text1
  - group2
    - text2
    - text3
    - group3
      - text4
    -  text5
- group4

**Comment by jocelynmutso** [comment]
![example-grouping drawio](https://github.com/dialob/dialob-parent/assets/47987958/4894a589-dc93-4762-9b52-3b884a8295d3)

**Comment by Tatuk** [comment]
we have a plan so i can close this issue
